import { expect, test } from '@playwright/test'

test('floating menu opens, traps focus, closes and reopens cleanly', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'MENU', exact: true })
  const menu = page.locator('#navigation-menu')
  await expect(trigger).toHaveAttribute('aria-expanded', 'false')
  await trigger.click()
  await expect(trigger).toHaveAttribute('aria-expanded', 'true')
  await expect(menu.locator('.menu-sections a')).toHaveCount(4)
  await expect(page.getByRole('button', { name: 'Close navigation menu' })).toBeFocused()
  for (let i = 0; i < 12; i++) await page.keyboard.press('Tab')
  expect(await menu.evaluate(node => node.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(menu).not.toBeVisible()
  await expect(trigger).toBeFocused()
  await trigger.click()
  await expect(menu).toHaveCSS('opacity', '1')
  await menu.locator('.menu-sections a[href="#contact"]').click()
  await expect(menu).not.toBeVisible()
  await expect(page).toHaveURL(/#contact$/)
})

test('compact phone menu keeps all destinations and close control in view', async ({ page }) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await page.goto('/')
  await page.getByRole('button', { name: 'MENU', exact: true }).click()
  const menu = page.locator('#navigation-menu')
  await expect(menu).toHaveAttribute('data-menu-state', 'open')
  await expect(menu.getByRole('link')).toHaveCount(6)
  await expect(menu.locator('.menu-social')).toBeInViewport()
  expect((await menu.locator('.menu-content').boundingBox())!.height).toBeLessThan(740)
  const close = page.getByRole('button', { name: 'Close navigation menu' })
  await expect(close).toBeInViewport()
  expect(await menu.evaluate(node => node.scrollWidth <= node.clientWidth)).toBe(true)
  await close.click()
  await expect(menu).not.toBeVisible()
})

test('curtain reverses on early close and navigation waits for it to finish', async ({ page }) => {
  await page.goto('/')
  const trigger = page.getByRole('button', { name: 'MENU', exact: true })
  const menu = page.locator('#navigation-menu')
  await trigger.click()
  await expect(menu).toHaveAttribute('data-menu-state', 'opening')
  await page.keyboard.press('Escape')
  await expect(menu).not.toBeVisible()
  await trigger.click()
  await expect(menu).toHaveAttribute('data-menu-state', 'open')
  const bounds = await menu.locator('.menu-content').boundingBox()
  expect(bounds!.height).toBeLessThanOrEqual(page.viewportSize()!.height * .65)
  await menu.locator('a[href="#about"]').click()
  await expect(menu).toHaveAttribute('data-menu-state', 'closing')
  expect(new URL(page.url()).hash).toBe('')
  await expect(menu).not.toBeVisible()
  await expect(page).toHaveURL(/#about$/)
  await expect(page.locator('#about')).toBeFocused()
})
